### ISSUE TITLE
[lit/reactive-element] - Cannot redefine property: size

### ISSUE THREAD

**Issue by siggerzz** [lit/lit#4383]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

Hey folks!

We've noticed an issue when using Lit components in NextJS applications (Only observed in Next 13 with `@lit-labs/nextjs`).

Originally, we thought this was an issue perhaps with Lit 2, however after attempting to upgrade our repos to Lit 3, we observed the same issue.

With the following dependencies:
```
  "dependencies": {
    ....
    // Our lit web component that's being consumed
    "@justeattakeaway/pie-button": "0.36.1",
    "@lit-labs/nextjs": "0.1.3",
    "next": "13.2.4",
    "react": "18.2.0",
    ...
}
```

We experience the following error:

```bash
info  - Linting and checking validity of types...
wc-next13:build:examples: warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
wc-next13:build:examples: info  - Creating an optimized production build...
wc-next13:build:examples: info  - Compiled successfully
wc-next13:build:examples: info  - Collecting page data...
wc-next13:build:examples: TypeError: Cannot redefine property: size
wc-next13:build:examples:     at defineProperty (<anonymous>)
wc-next13:build:examples:     at h.createProperty (/Users/ben.siggery/Code/pie/apps/examples/wc-next13/.next/server/chunks/337.js:279:1207)
wc-next13:build:examples:     at /Users/ben.siggery/Code/pie/apps/examples/wc-next13/.next/server/chunks/337.js:304:754
wc-next13:build:examples:     at /Users/ben.siggery/Code/pie/apps/examples/wc-next13/.next/server/chunks/337.js:304:841
wc-next13:build:examples:     at g (/Users/ben.siggery/Code/pie/apps/examples/wc-next13/.next/server/pages/index.js:730:29)
wc-next13:build:examples:     at 686 (/Users/ben.siggery/Code/pie/apps/examples/wc-next13/.next/server/pages/index.js:811:1)
wc-next13:build:examples:     at __webpack_require__ (/Users/ben.siggery/Code/pie/apps/examples/wc-next13/.next/server/webpack-runtime.js:25:42)
wc-next13:build:examples:     at /Users/ben.siggery/Code/pie/apps/examples/wc-next13/.next/server/pages/index.js:22:96
wc-next13:build:examples:     at __webpack_require__.a (/Users/ben.siggery/Code/pie/apps/examples/wc-next13/.next/server/webpack-runtime.js:89:13)
wc-next13:build:examples:     at 97 (/Users/ben.siggery/Code/pie/apps/examples/wc-next13/.next/server/pages/index.js:11:21)
```

Running `yarn why @lit/reactive-element` results in the following dependants of this package:

```
❯ yarn why @lit/reactive-element
├─ @lit-labs/ssr-client@npm:1.1.5
│  └─ @lit/reactive-element@npm:2.0.1 (via npm:^1.6.1 || ^2.0.0)
│
├─ @lit-labs/ssr@npm:3.1.9
│  └─ @lit/reactive-element@npm:2.0.1 (via npm:^1.6.1 || ^2.0.0)
│
├─ @open-wc/scoped-elements@npm:2.2.4
│  └─ @lit/reactive-element@npm:2.0.1 (via npm:^1.0.0 || ^2.0.0)
│
├─ lit-element@npm:4.0.1
│  └─ @lit/reactive-element@npm:2.0.1 (via npm:^2.0.0)
│
└─ lit@npm:3.0.2
   └─ @lit/reactive-element@npm:2.0.1 (via npm:^2.0.0)
```

From our testing, we believe that removing this line fixes the problem: - https://github.com/justeattakeaway/pie/blob/main/apps/examples/wc-next13/pages/index.tsx#L17

Also, I'm not sure if it's worth the Lit team rethinking how dependencies are resolved, the usage of `^` in some of the Lit packages has come to bite us a few times in our repo, and in our own experiences, we've found that using exact versions is less prone to causing errors for consumers.

### Reproduction

You should be able to reproduce the error in the following branch of our Design System repo:

https://github.com/justeattakeaway/pie/pull/978

1). Clone the repo
2). Run `yarn`
3) Remove the `.turbo/config.json` file (We use Turborepo remote caching in our repo and you won't have access to the token, so this prevents build failure)

4) Run `yarn build:examples --filter=wc-next13`

### Workaround

A temporary workaround is to set the following in the `package.json` at the root of our monorepo:

```
"resolutions" : {
    < - This was already present - >
    "@babel/traverse": "7.22.5"
    < - Force dependants to resolve 1.6.3 as the error no longer occurs - >
    "@lit/reactive-element": "1.6.3",
}
```

Whilst this work around fixes the issue with our `wc-next13` package, it does however cause errors our other packages notably wc-angular12.

Because of this, we're blocked on upgrading until this issue gets resolved.

```
Error: wc-angular12#build:examples: command (/home/runner/work/pie/pie/apps/examples/wc-angular12) yarn run build:examples exited (1)
   ERROR  run failed: command  exited (1)
  cache miss, executing 1eeb9f4bf715cfc7
  - Generating browser application bundles (phase: setup)...
  ✔ Browser application bundle generation complete.
  ✔ Browser application bundle generation complete.
  
  Error: Error: ../../../node_modules/lit-element/lit-element.d.ts:93:15 - error TS2416: Property 'createRenderRoot' in type 'LitElement' is not assignable to the same property in base type 'ReactiveElement'.
    Type '() => HTMLElement | DocumentFragment' is not assignable to type '() => Element | ShadowRoot'.
      Type 'HTMLElement | DocumentFragment' is not assignable to type 'Element | ShadowRoot'.
        Type 'DocumentFragment' is not assignable to type 'Element | ShadowRoot'.
          Type 'DocumentFragment' is missing the following properties from type 'ShadowRoot': delegatesFocus, host, mode, onslotchange, and 11 more.
  
  93     protected createRenderRoot(): HTMLElement | DocumentFragment;
```

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Breaks in 2.0.1, worked in 1.6.3

### Browser/OS/Node environment

OS: MacOS / Windows / Ubuntu
Node: Tested in Node 18 / 20
npm version: 10.1.0

**Comment by sorvell** [comment]
Your decorator `@validPropertyValues` [defines the property](https://github.com/justeattakeaway/pie/blob/main/packages/components/pie-webc-core/src/decorators/valid-property-values.ts#L11-L32) defines properties such that they cannot be configured. In Lit3, existing property accessors are wrapped by default. This is new behavior in Lit 3 v. Lit 2 so I can't explain why you're seeing the issue in Lit 2.

Here's a repro (note, the playground still uses Lit2 so to recreate the issue I copied relevant code changes in from Lit 3): https://lit.dev/playground/#gist=acbbfc63d4816ded4ac3864b90441ba7.

Try adding `{noAccessor: true}` to you calls to the `@property` decorator when you use `@validPropertyValues` (e.g. [here in the pie-button](https://github.com/justeattakeaway/pie/blob/main/packages/components/pie-button/src/index.ts#L75)).

If this is a correct diagnosis and fix, you'll likely hit another error on the next use of those 2 decorators together. For that reason, you'll likely want to change your decorators to make them set `configurable: true` (and then you don't need to use `{noAccessor: true}` all over the place). Once you do that you can remove the call to `requestUpdate` in your decorators since Lit will call that for you in the wrapped accessor.

**Comment by augustjk** [comment]
^^ I was writing it all and @sorvell beat me to it!

**Comment by augustjk** [comment]
btw @sorvell, newly created playgrounds from lit.dev/playground use Lit 3. If you're modifying from an existing playground link, it can still have Lit 2. This can be updated by creating a `package.json` file and modifying the versions.

**Comment by siggerzz** [comment]
This worked perfectly, thanks so much to you both! 🎉
