### PR TITLE
[reactive-element] Make decorators accept `ReactiveElement` from elsewhere

### LINKED ISSUE #3241: [reactive-element] Type 'Component' is not assignable to type 'ReactiveElement'. Types have separate declarations of a private property '__instanceProperties'.
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

With lit@2.2.8 lit decorators works as expected, but if I wanted to upgrade to 2.3.0 or above I get this typescript error:

```
component.ts: error TS2345: Argument of type 'Component' is not assignable to parameter of type 'ReactiveElement | ClassElement'.
  Type 'Component' is not assignable to type 'ReactiveElement'.
    Types have separate declarations of a private property '__instanceProperties'.
```

Component code:
```
export class Component extends LitElement {
	@query('[part="feedback"]') readonly $feedback!: HTMLElement;
	...
}
```

image

### Reproduction

I didn't had time to create a reproduction repo, but if it's needed I can make.

We use the following tsconfig.json compilerOptions:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "es2018",
    "module": "esnext",
    "moduleResolution": "node",
    "declaration": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "useDefineForClassFields": false,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts"
  ]
}

```

### Workaround

Workaround is to use 2.2.x version

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing since 2.3.0, worked in 2.2.8

### Browser/OS/Node environment

node: 16.15.1
typescript: 4.7.4
OS: macOS 12.5

### PR DESCRIPTION
**Pull request by augustjk**
Fixes #3241 

This specifically affected decorators made with `decorateProperty` which also includes the labs/context decorators. This is a workaround until something like https://github.com/microsoft/TypeScript/issues/52119 is implemented.

Manually tested by creating a project with multiple versions of `reactive-element` installed, and replacing the nested version with one built with these changes applied.

### CODE REVIEW

**Review by rictic — APPROVED** [review]

File: packages/reactive-element/src/decorators/base.ts [hunk 1]
```diff
@@ -6,6 +6,10 @@
 
 import {ReactiveElement} from '../reactive-element.js';
 
+export type Interface<T> = {
```
[the remark this answers is not in the document]
Comment (augustjk) [reply packages/reactive-element/src/decorators/base.ts:14]: Good suggestion. Added!

**Review by rictic — APPROVED** [review]
Great!

File: packages/reactive-element/src/decorators/base.ts [hunk 2]
```diff
@@ -71,7 +80,7 @@ export const decorateProperty =
     descriptor?: (property: PropertyKey) => PropertyDescriptor;
   }) =>
   (
-    protoOrDescriptor: ReactiveElement | ClassElement,
+    protoOrDescriptor: Interface<ReactiveElement> | ClassElement,
```
Comment (justinfagnani) [inline packages/reactive-element/src/decorators/base.ts:83]: Just a note: we should have use function overload signatures here.

**Review by justinfagnani — APPROVED** [review]
