### ISSUE TITLE
[reactive-element] Type 'Component' is not assignable to type 'ReactiveElement'. Types have separate declarations of a private property '__instanceProperties'.

### ISSUE THREAD

**Issue by petergaal91** [lit/lit#3241]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

With lit@2.2.8 lit decorators works as expected, but if I wanted to upgrade to 2.3.0 or above I get this typescript error:

```
component.ts: error TS2345: Argument of type 'Component' is not assignable to parameter of type 'ReactiveElement | ClassElement'.
  Type 'Component' is not assignable to type 'ReactiveElement'.
    Types have separate declarations of a private property '__instanceProperties'.
```

Component code:
```
export class Component extends LitElement {
	@query('[part="feedback"]') readonly $feedback!: HTMLElement;
	...
}
```

![image](https://user-images.githubusercontent.com/8919920/186157901-4089aafe-712a-438d-bdb0-bff3043a2dae.png)

### Reproduction

I didn't had time to create a reproduction repo, but if it's needed I can make.

We use the following tsconfig.json compilerOptions:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "es2018",
    "module": "esnext",
    "moduleResolution": "node",
    "declaration": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "useDefineForClassFields": false,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts"
  ]
}

```

### Workaround

Workaround is to use 2.2.x version

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing since 2.3.0, worked in 2.2.8

### Browser/OS/Node environment

node: 16.15.1
typescript: 4.7.4
OS: macOS 12.5

**Comment by SketchBookkeeper** [comment]
I'm seeing this issue as well with Lit 2.3.1. 

node: 16.17.0
typescript: 4.7.4
OS: Windows 11

**Comment by SketchBookkeeper** [comment]
I ran `npm dedupe` which fixed the issue.

**Comment by codeth** [comment]
Also seeing the same with `2.3.1`. Downgrading to `2.2.8` fixed it.

**Comment by RoXuS** [comment]
same here, we can't go to `2.3.0` and above:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/3296671/187712935-3a5543dd-3a32-49a1-b5fe-7d947511d110.png">

**Comment by augustjk** [comment]
The problem is there are likely multiple versions of `@lit/reactive-element` installed which can be checked by `npm ls `@lit/reactive-element`.

It's probably something like:
```
lit@2.3.1
└─┬ @lit/reactive-element@1.4.1
  └─┬ lit-element@3.2.2
    └── @lit/reactive-element@1.3.4
```

This would happen for existing projects that update `lit` to the latest version because we bumped `@lit/reactive-element` but not `lit-element` causing this duplication.

As @SketchBookkeeper pointed out, `npm dedupe` would fix this by removing the older version of `@lit/reactive-element`.

To prevent this from happening when updating `lit`, we should publish a patch to `lit-element` to depend on the same minimum version of `@lit/reactive-element` and patch `lit` to up the version of `lit-element` it depends on.

A potential longer discussion is whether we want to avoid using private class fields so we just rely on structural typing and allow for multiple instance interop like these w/o type errors.

**Comment by augustjk** [comment]
I'm actually curious how others got to the point of seeing this error and what their `package.json` might look like?

I can reproduce this error by installing a specific version of `@lit/reactive-element` but if I just update `lit`, it seems to update and dedupe dependencies fine.

I suspect those who are seeing this might also have a specifically mentioned dependency on `@lit/reactive-element` in the `package.json`.

**Comment by petergaal91** [comment]
The reason why we have two different version is @open-wc/testing

```
o Reasons this module exists
   - "_project_#@strivacity#elements" depends on it
   - Hoisted from "_project_#@strivacity#elements#lit"
info Disk size without dependencies: "3.67MB"
info Disk size with unique dependencies: "6.58MB"
info Disk size with transitive dependencies: "6.61MB"
info Number of shared dependencies: 4
=> Found "@open-wc/testing-helpers#lit@2.2.8"
info This module exists because "_project_#@strivacity#elements#@open-wc#testing#@open-wc#testing-helpers" depends on it.
info Disk size without dependencies: "676KB"
info Disk size with unique dependencies: "3.57MB"
info Disk size with transitive dependencies: "3.59MB"
info Number of shared dependencies: 4
```

**Comment by codeth** [comment]
@augustjk We use yarn, so `yarn dedupe` was useless in our case:

`error The dedupe command isn't necessary. `yarn install` will already dedupe.` 😂

I ran into this issue updating from `lit-element@2.5.0`, `lit-html@1.4.1` and `@open-wc/testing@3.1.6`. Multiple versions of `@lit/reactive-element` were listed in the `yarn.lock`, despite running `yarn remove lit-element lit-html` before `yarn add lit`.

I've now fixed the issue by manually deduping my `yarn.lock`.

**Comment by stefanholzapfel** [comment]
@augustjk I' also experience that issue. In my case I can see another version of reactive-element which comes from using shoelac.stye@2.0.0-beta.82 and @lit-labs/motion@1.0.3

**Comment by augustjk** [comment]
Root cause of this error:
`lit` package re-exports `LitElement` from the `lit-element` package which has its own dependency on `@lit/reactive-element`
`lit` package re-exports all decorators from a direct dependency on `@lit/reactive-element`.

Therefore, the version of `@lit/reactive-element` for `LitElement` could potentially be different than the decorators.

Workarounds:
Dedupe the versions of `@lit/reactive-element` so there's only one.

Or,

make sure `LitElement` and the decorators come from the same package.
```js
import {LitElement} from 'lit-element';
import {query} from 'lit-element/decorators.js';
```

We should fix it so that importing everything straight from `lit` should be fine even with multiple versions.

Potential options for fix:
1. Don't use `private` properties in classes which make the class types from different versions incompatible.
2. Drop the direct dependency of `@lit/reactive-element` from `lit` and rely on it being a transitive dependency via `lit-element`. Change the re-exports of decorators in the `lit` package to come from `lit-element/decorators.js` instead.

I think option 2 makes more sense to me.

**Comment by augustjk** [comment]
> 2. Drop the direct dependency of `@lit/reactive-element` from `lit`

So we actually don't want to change our dependency graph as that will cause an additional waterfall of dependency request when unbundled.

The best solution seems to still be to make sure `@lit/reactive-element` is deduped.

For npm users, `npm dedupe` seems to do its job well.

For yarn users, I'm not too familiar with it myself and having trouble replicating the issue. I see that `yarn dedupe` doesn't work the same way as npm, but `yarn install` seems to try and dedupe everything according to version markers. `yarn upgrade @lit/reactive-element` might also help to nudge it to be the same latest version.

If you're still having this issue, please let us know.

**Comment by Himself65** [comment]
same error here

**Comment by augustjk** [comment]
`@lit/reactive-elemenet@1.6.2` was just released which includes the fix for this. Specifically the decorators need to come from the latest `@lit/reactive-element`, and it can then be applied to fields on classes extending other versions of `lit-element` or `@lit/reactive-element`.
